### ISSUE TITLE
Please give example of input images

### ISSUE THREAD

**Issue by manhnguyen92** [htyjers/DGTS-Inpainting#1]
Please give me example of input images which include mask and image

**Comment by htyjers** [comment]
I random choose the image and mask from the Places2, CelebA and PSV to show, you can choose mask in [https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/test.py#L115-L116](url) from the [https://nv-adlr.github.io/publication/partialconv-inpainting](url) to output your own inpainted image.
