### ISSUE TITLE
Doubt about the paper:Figure 5

### ISSUE THREAD

**Issue by Marcelo5444** [htyjers/DGTS-Inpainting#11]
Cant understand the blue square in the legend, its says Inpainting patches. But i am not sure what kind of patches are those, is it clear to me the coarsely filled patches and the known patches.

**Comment by htyjers** [comment]
Thank you for attention. In each round, we inpaint all the coarse patches and only select the one best patch to exist, the others coarse patches will follow the rules in the next round, our proposed Computational efficiency is related to this rules, our paper detailedly explain that.
