### ISSUE TITLE
Doubt about the Paper: figure 9

### ISSUE THREAD

**Issue by Marcelo5444** [htyjers/DGTS-Inpainting#12]
How do you generate the structure information image (column d) given a rgb image

**Comment by Marcelo5444** [comment]
Could you please tell me the reference paper pls?

**Comment by htyjers** [comment]
Thank you for attention. By Canny Edge Detection, you can take [these](https://github.com/knazeri/edge-connect/blob/master/src/dataset.py) into consideration.
