### ISSUE TITLE
How to test？

### ISSUE THREAD

**Issue by CodeMadUser** [htyjers/DGTS-Inpainting#3]
hello, it's an amazing work.But I don't known how to test it,where should the test image, the Upsampler code and  Upsampler's pretrain and the corresponding mask image be placed respectively?  I'm looking forward to your replying.thanks.

**Comment by htyjers** [comment]
Thank you for attention, I have already combine the Upsampler code with my model code in my test folder. After our model inpaints the masked image, the Upsampler will directly restore it into higher resolution without other code. You can download the corresponding pretained model from [here](https://github.com/yingchen001/BAT-Fill)  and set in [here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/test.py#L100)

**Comment by CodeMadUser** [comment]
> 

thank you.I am trying it on, Where does the corresponding pretained model need to be placed in the code?

**Comment by htyjers** [comment]
> thank you.I am trying it on, Where does the corresponding pretained model need to be placed in the code?

Upsampler : [Here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/test.py#L100)
Our model: [Here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/test.py#L106)

**Comment by CodeMadUser** [comment]
> > thank you.I am trying it on, Where does the corresponding pretained model need to be placed in the code?
> 
> Upsampler : [Here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/test.py#L100) Our model: [Here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/test.py#L106)

thanks for your sharing.I'll trying it on.

**Comment by CodeMadUser** [comment]
> > thank you.I am trying it on, Where does the corresponding pretained model need to be placed in the code?
> 
> Upsampler : [Here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/test.py#L100) Our model: [Here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/test.py#L106)

thank you for sharing.codes runs,but I don't known why  does'n it does'n generate the result.could you give me some advice?Here is my folder directory。

![image](https://user-images.githubusercontent.com/97572749/198591877-881f2720-beaa-41ab-93e4-97c5a5376169.png)
![image](https://user-images.githubusercontent.com/97572749/198592503-d23883ef-91f9-4bdf-b2aa-5c9b3b635d9a.png)
![image](https://user-images.githubusercontent.com/97572749/198599540-9518b113-f3d5-43ba-a4a1-c4732edeb524.png)
![image](https://user-images.githubusercontent.com/97572749/198593081-60bd84e2-d523-4a27-8854-a3361a4ae5ef.png)

**Comment by 12op** [comment]
I also encountered the same problem, no error was reported during the test, and no results were generated
![image](https://user-images.githubusercontent.com/94891134/198593912-64466796-8800-4dce-a9ce-ef3f2101465f.png)

**Comment by htyjers** [comment]
> I also encountered the same problem, no error was reported during the test, and no results were generated ![image](https://user-images.githubusercontent.com/94891134/198593912-64466796-8800-4dce-a9ce-ef3f2101465f.png)

You should set your test dataset [here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/run_train.py#L9). 
for test, the Folder Format is below:
-places2
-- test

Please set the [batchsize](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/main.py#L17)=1 and make sure you can successful load the corresponding pretrained model,

**Comment by htyjers** [comment]
@12op @CodeMadUser  I have updated the Readme file and code for more clear descriptions thank you for your attention.

**Comment by CodeMadUser** [comment]
> @12op @CodeMadUser I have updated the Readme file for more clear descriptions thank you for your attention.

thanks for your helping.If I want to try experimenting with a single figure, what code would I need to change?

**Comment by htyjers** [comment]
> > @12op @CodeMadUser I have updated the Readme file for more clear descriptions thank you for your attention.
> 
> thanks for your helping.If I want to try experimenting with a single figure, what code would I need to change?

I fix the batchsize for test in [here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/main.py#L17), you can also set your Folder name for test in [here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/main.py#L19).

**Comment by CodeMadUser** [comment]
> > > @12op @CodeMadUser I have updated the Readme file for more clear descriptions thank you for your attention.
> > 
> > 
> > thanks for your helping.If I want to try experimenting with a single figure, what code would I need to change?
> 
> I fix the batchsize for test in [here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/main.py#L17), you can also set your filename for test in [here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/main.py#L19).

ok.thank you for your advice and contributions.I'll try it on soon.

**Comment by zhangshilong2000** [comment]
您好，我在测试中遇到和你一样的问题，可以加QQ交流一下吗

**Comment by zhangshilong2000** [comment]
@12op 
![image](https://github.com/htyjers/DGTS-Inpainting/assets/72057128/a054fa6f-920b-43d8-8735-5e916beb9fd4)
您好，这种问题是如何解决的？

**Comment by skaasr** [comment]
> @12op ![image](https://private-user-images.githubusercontent.com/72057128/273605510-a054fa6f-920b-43d8-8735-5e916beb9fd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMTA3MTQsIm5iZiI6MTcxOTExMDQxNCwicGF0aCI6Ii83MjA1NzEyOC8yNzM2MDU1MTAtYTA1NGZhNmYtOTIwYi00M2Q4LTg3MzUtNWU5MTZiZWI5ZmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDAyNDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZmE5ZjZkZjA4NThlNjhhNjc3MTgyZjYzYjc5ZjU5NDk0Nzg4ZTY0MDRhYmU4NjVhNDM5ODRhZjFiNmVmODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tb0Be4LvPG5e-_5gJFgEAQu1V2-oG_-WKNzWbq5BP3c) 您好，这种问题是如何解决的？

我也出现了这种问题，请问如何解决
