### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0?

### ISSUE THREAD

**Issue by watertianyi** [htyjers/DGTS-Inpainting#4]

**Comment by htyjers** [comment]
![image](https://user-images.githubusercontent.com/97180052/199138437-211daa6e-2253-4bd9-bbe4-8490b055728e.png)
Sorry, I cannot find this parameter in my code. Please double check that.

**Comment by watertianyi** [comment]
input image dir error

**Comment by htyjers** [comment]
> input image dir error

Prepare testing datasets and put them in ./data/places2/test and you can set the datadir in [here](https://github.com/htyjers/DGTS-Inpainting/blob/DGTS/code/test/run_train.py#L9). The readme file also explain that, thank you
