### ISSUE TITLE
where is the  path of Upsampler pretrained network

### ISSUE THREAD

**Issue by zborger** [htyjers/DGTS-Inpainting#6]
您好，非常感谢您提供这么优秀的工作，我在测试的过程中遇到一些问题，期待您的解答。
我在训练好模型之后得到了transforme64中的generate的预训练模型。
但是当我在测试的时候发现多了一个upsamplergenerator的预训练模型，但是我在训练的时候并没有训练这个模型，请问这个模型的预训练模型需要从哪下载啊，还是需要我自己训练，若需要自己训练又该如何训练呢。

**Comment by htyjers** [comment]
Thank you for your attention, we directly adopt the upsampler from [here](https://github.com/yingchen001/BAT-Fill). We have already put the upsampler code in the testing file, you only need to download the corresponding pretrained model for upsampler . The readme file also explain that.
