### ISSUE TITLE
Where I can find the code for the representation of patches relation and where they have moved.

### ISSUE THREAD

**Issue by Marcelo5444** [htyjers/DGTS-Inpainting#7]
How I can recreate the (c-i) image in figure 4.

Thank you in advance.

**Comment by htyjers** [comment]
Thank you for attention, you can borrow the code from [here](https://github.com/facebookresearch/detr)->'Notebooks' to visiual the relationships.

**Comment by Marcelo5444** [comment]
Hi, sorry but could it find it! All I found was plot for attention maps, no individual patches.
