### ISSUE TITLE
Question about patch embedding and update_mask2

### ISSUE THREAD

**Issue by Marcelo5444** [htyjers/DGTS-Inpainting#8]
What is the reason behinf all the code in patch_embedding.py in the forward (line 30). The update mask sets to 1 all the pixels that fall within a patch if some of them are masked?

**Comment by htyjers** [comment]
Thank you, we use the weight_maskUpdater(kernel size equal patch size and it's value is one) to  slide all patches to calculate the mask ratio of different patches, update_mask2 is used to calculate the coarsely filled module to order the masked patches.
